//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGarageSale.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAudit
    {
        public System.Guid AuditId { get; set; }
        public System.DateTime RevisionStamp { get; set; }
        public string TableName { get; set; }
        public string UserId { get; set; }
        public string Actions { get; set; }
        public string OldData { get; set; }
        public string NewData { get; set; }
        public string ChangedColumns { get; set; }
        public string TableIdValue { get; set; }
    }
}
