//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swoopinn.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBranch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBranch()
        {
            this.tblCustomerBranches = new HashSet<tblCustomerBranch>();
        }
    
        public System.Guid IdBranch { get; set; }
        public string Address { get; set; }
        public string MobilePhone { get; set; }
        public string LaneLine { get; set; }
        public string Email { get; set; }
        public System.Guid IdCity { get; set; }
        public string Name { get; set; }
        public int updateSec { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerBranch> tblCustomerBranches { get; set; }
    }
}
