//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swoopinn.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomer()
        {
            this.tblCustomerBranches = new HashSet<tblCustomerBranch>();
        }
    
        public System.Guid IdCustomer { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string NickName { get; set; }
        public string HomeAddress { get; set; }
        public string Passport { get; set; }
        public System.Guid IdHomeCountry { get; set; }
        public System.Guid IdHomeState { get; set; }
        public Nullable<System.Guid> IdHomeCity { get; set; }
        public string CurrentAddress { get; set; }
        public System.Guid IdCurrentCountry { get; set; }
        public Nullable<System.Guid> IdCurrentCity { get; set; }
        public string Email { get; set; }
        public string MobilePhone { get; set; }
        public string LaneLinePhone { get; set; }
        public string CountryUIdentification { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<System.Guid> IdCurrentVisa { get; set; }
        public Nullable<System.DateTime> VisaExpireDate { get; set; }
        public Nullable<System.Guid> IdCurrentOSHC { get; set; }
        public Nullable<System.DateTime> OSHCExpireDate { get; set; }
        public Nullable<System.Guid> IdSocialNetwork { get; set; }
        public Nullable<System.Guid> IdHighestEduType { get; set; }
        public string HighestEduDescription { get; set; }
        public string HighestEduInstiName { get; set; }
        public Nullable<System.DateTime> HighestGraduationDate { get; set; }
        public Nullable<System.Guid> IdCurrentEduType { get; set; }
        public Nullable<System.Guid> IdCurrentEduSchool { get; set; }
        public Nullable<System.DateTime> IdCurrentEduStartDate { get; set; }
        public Nullable<System.DateTime> IdCurrentEduEndDate { get; set; }
        public Nullable<System.Guid> IdMaritalStatus { get; set; }
        public Nullable<int> Age { get; set; }
        public string JobExperience { get; set; }
        public string EnglishTest { get; set; }
        public string EnglishTestScore { get; set; }
        public Nullable<int> YearExperience { get; set; }
        public string UrlImage { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public System.Guid IdCreateUser { get; set; }
        public System.Guid IdUpdateUser { get; set; }
        public int UpdateSecuence { get; set; }
    
        public virtual tblGeolocation tblGeolocation { get; set; }
        public virtual tblGeolocation tblGeolocation1 { get; set; }
        public virtual tblGeolocation tblGeolocation2 { get; set; }
        public virtual tblGeolocation tblGeolocation3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerBranch> tblCustomerBranches { get; set; }
    }
}
