//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swoopinn.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGeolocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGeolocation()
        {
            this.tblCustomers = new HashSet<tblCustomer>();
            this.tblCustomers1 = new HashSet<tblCustomer>();
            this.tblCustomers2 = new HashSet<tblCustomer>();
            this.tblCustomers3 = new HashSet<tblCustomer>();
        }
    
        public System.Guid IdPlace { get; set; }
        public string Name { get; set; }
        public int PlaceType { get; set; }
        public Nullable<System.Guid> IdParent { get; set; }
        public int Status { get; set; }
        public string IdExternal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomer> tblCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomer> tblCustomers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomer> tblCustomers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomer> tblCustomers3 { get; set; }
    }
}
