//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGarageSale.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        public System.Guid IdItem { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string urlImage { get; set; }
        public System.Guid IdGarageSale { get; set; }
    
        public virtual tblGarageSale tblGarageSale { get; set; }
    }
}
